apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: rhods
  labels:
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/instance: rhods
    app.kubernetes.io/part-of: rhods-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rhods-operator
spec:
  components:
    codeflare:
      managementState: Managed
    dashboard:
      managementState: Managed
    datasciencepipelines:
      managementState: Managed
    kserve:
      managementState: Managed
      serving:
        managementState: Managed
        name: knative-serving
        ingressGateway:
          certificate:
            type: SelfSigned
    modelmeshserving:
      managementState: Managed
    ray:
      managementState: Managed
    trustyai:
      managementState: Managed
    workbenches:
      managementState: Managed
